export const APPLY_COUPON_REQUEST = "APPLY_COUPON_REQUEST"
export const APPLY_COUPON_SUCCESS = "APPLY_COUPON_SUCCESS"
export const APPLY_COUPON_FAIL = "APPLY_COUPON_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"