export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const CUSTOMER_SIGNUP_REQUEST = "CUSTOMER_SIGNUP_REQUEST"
export const CUSTOMER_SIGNUP_SUCCESS = "CUSTOMER_SIGNUP_SUCCESS"
export const CUSTOMER_SIGNUP_FAIL = "CUSTOMER_SIGNUP_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"