export const GET_PACKAGES_REQUEST = "GET_PACKAGES_REQUEST"
export const GET_PACKAGES_SUCCESS = "GET_PACKAGES_SUCCESS"
export const GET_PACKAGES_FAIL = "GET_PACKAGES_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"