export const GET_PRICES_REQUEST = "GET_PRICES_REQUEST"
export const GET_PRICES_SUCCESS = "GET_PRICES_SUCCESS"
export const GET_PRICES_FAIL = "GET_PRICES_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"