export const GET_SERVICES_REQUEST = "GET_SERVICES_REQUEST"
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS"
export const GET_SERVICES_FAIL = "GET_SERVICES_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"